### ISSUE TITLE
Example and flask_appfactory.ext.jinja2

### ISSUE THREAD

**Issue by berghaus** [inveniosoftware/flask-appfactory#4]
I first bumped into this following the example instructions, then replicated it by checking out the examples from github page. I started with a fresh 14.04 Ubuntu VM. Then installed AppFactory:

```
sudo pip install Flask-AppFactory
cd ~/flask-appfactory/examples
sudo python setup.py install
```

And then trying out the application:

```
$ myapp testsimple
Test
$ myapp testapp
Traceback (most recent call last):
  File "/usr/local/bin/myapp", line 9, in <module>
    load_entry_point('MyApp==1.0', 'console_scripts', 'myapp')()
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 664, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/flask_cli/cli.py", line 343, in main
    return AppGroup.main(self, *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 644, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 991, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 837, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 464, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/flask_cli/cli.py", line 209, in decorator
    with __ctx.ensure_object(ScriptInfo).load_app().app_context():
  File "/usr/local/lib/python2.7/dist-packages/flask_cli/cli.py", line 185, in load_app
    rv = self.create_app(self)
  File "/usr/local/lib/python2.7/dist-packages/flask_appfactory/cli.py", line 85, in create_cli_app
    load_application(app)
  File "/usr/local/lib/python2.7/dist-packages/flask_appfactory/app.py", line 126, in load_application
    extensions=ExtensionRegistry(app),
  File "/usr/local/lib/python2.7/dist-packages/flask_registry/registries/appdiscovery.py", line 153, in __init__
    self.register(app, ext_name)
  File "/usr/local/lib/python2.7/dist-packages/flask_registry/registries/appdiscovery.py", line 163, in register
    ext = import_string(ext_name)
  File "/usr/local/lib/python2.7/dist-packages/werkzeug/utils.py", line 437, in import_string
    sys.exc_info()[2])
  File "/usr/local/lib/python2.7/dist-packages/werkzeug/utils.py", line 425, in import_string
    module = import_string(module_name)
  File "/usr/local/lib/python2.7/dist-packages/werkzeug/utils.py", line 437, in import_string
    sys.exc_info()[2])
  File "/usr/local/lib/python2.7/dist-packages/werkzeug/utils.py", line 430, in import_string
    raise ImportError(e)
werkzeug.utils.ImportStringError: import_string() failed for 'flask_appfactory.ext.jinja2'. Possible reasons are:

- missing __init__.py in a package;
- package or module path not included in sys.path;
- duplicated package or module name taking precedence in sys.path;
- missing module, class, function or variable;

Debugged import:

- 'flask_appfactory' found in '/usr/local/lib/python2.7/dist-packages/flask_appfactory/__init__.pyc'.
- 'flask_appfactory.ext' not found.

Original exception:

ImportStringError: import_string() failed for 'flask_appfactory.ext'. Possible reasons are:

- missing __init__.py in a package;
- package or module path not included in sys.path;
- duplicated package or module name taking precedence in sys.path;
- missing module, class, function or variable;

Debugged import:

- 'flask_appfactory' found in '/usr/local/lib/python2.7/dist-packages/flask_appfactory/__init__.pyc'.
- 'flask_appfactory.ext' not found.

Original exception:

ImportError: 'module' object has no attribute 'ext'
```

trying to run the server or shell looks the same. Any obvious things I am missing?

**Comment by lnielsen** [comment]
Can you try to open a Python shell and run:

``` python
import flask_appfactory.ext.jinja2
```

It should exist, so probably there's an import error inside the module due to some missing pip dependency:

https://github.com/inveniosoftware/flask-appfactory/blob/master/flask_appfactory/ext/jinja2.py

**Comment by berghaus** [comment]
Trying the import gives me an ImportError:

```
>>> import flask_appfactory.ext.jinja2
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: No module named ext.jinja2
```

This however works:

```
from flask_appfactory.ext import jinja2
```

**Comment by lnielsen** [comment]
Found and fixed the problem. It was due to problem in `setup.py`.
